- learn/index.html
@garyb @hdgarrood Does this look ok? I thought Try PS was on there before but I guess not.
> Add new learning resources

- download/index.html
[The package](https://chocolatey.org/packages/purescript).
> Add chocolatey package.

- learn/eff/index.html
- learn/eff/index.markdown
- learn/index.html
> Eff article

- learn/index.html
- learn/quickcheck/index.html
- learn/quickcheck/index.html1
- learn/quickcheck/index.markdown
/cc @garyb 
We might want to consider changing the article list to a plain `ul`, what do you think?
Also, it might be nice to list the most recent article on the home page somewhere, with a link?
> QuickCheck article

- learn/index.html
> Add link to "Better know a language" talk

- download/index.html
> Info on tools, fix #42

- learn/index.html
> Add Thermite article link

- projects/index.html
@quephird @garyb How's this?
[Preview](https://rawgit.com/purescript/purescript.github.io/space-invaders/projects/)
> Add space invaders

- learn/getting-started/index.html
- learn/getting-started/index.markdown
... To use the [npm package](https://www.npmjs.com/package/purescript), to hopefully make it easier to get going.
> Tweaks the "Getting Started" post's psc installation instructions

- learn/index.html
I only copied and filled out the slots from one of the existing talk cards. Probably check if it looks fine before merging...
> adds fby talk

- learn/index.html
I also corrected some markup... looks like there was some confusion with `<ul>` and `<li>` going on
> move fby talk to the front of the talk list

- index.html
> Update examples on front page

- _site/learn/index.html
- learn/index.html
> Pull out community section on Learn page

- _site/projects/index.html
- projects/index.html
> added SandScript, clicker-builder

- _site/learn/index.html
- _site/learn/partial/index.html
- learn/index.html
- learn/partial/index.markdown
> Add Partial type class article

- community/index.html
- download/index.html
- generator/community/index.html
- generator/download/index.html
- generator/index.html
- generator/learn/index.html
- index.html
- learn/index.html
- Newer, relevant examples, with Try PureScript links
- Remove out-of-date links and update the online meetups link
- Link to the new documentation repo instead of the wiki
> Various updates

- _generator/learn/quickcheck/index.markdown
- learn/quickcheck/index.html
[Snippet in try purescript](http://try.purescript.org/?gist=90b247c05ef52ed0f2fdbac1c6fec6b8&backend=core).
> fix for a bug in the quickcheck article

- index.html
Change `import import Flare` to `import Flare`, on the homepage.
> Fix syntax

- _generator/learn/getting-started/index.markdown
- learn/getting-started/index.html
Remove let bindings.
Also make it clear dependencies should be installed.
> Getting started 0.11 updates

- index.html
Small mistake from my recent branch
> Use relative URLs

- index.html
> Add attribution for logo

- index.html
Requested in https://github.com/purescript/purescript.github.io/issues/125
I didn't test this locally yet. Wanted to get a PR out first.
> Add community section to home page.

- index.html
> Emphasize doc repo

- index.html
Fixes #143 
Funny how I originally removed this a year ago.
> Re-add link to updated version of PS book
