download/index.html
I only found commands for two, but others can be added later. In particular, a Chocolatey package for Windows would be nice.
=> Add package manager section to Download page

download/index.html
Now we can install PureScript via [npm](https://www.npmjs.com/) since I created [`purescript`](https://www.npmjs.com/package/purescript) npm package.
```sh
$ npm install -g purescript
$ psc --help
$ psc-docs --help
$ psc-make --help
$ psci --help
```
=> Add installation instruction via npm

index.html
This removes the bulky type signatures on the examples, and updates the `Parallel` example to use `Control.Parallel`.
/cc @garyb
=> Simplify code in examples

download/index.html
This simplifies a few things:
- Only recommend the following installation approaches, which are the most stable, in this order:
- Binaries
- NPM
- Homebrew
- Stack
- Remove installation instructions for latest master, since that is a use case almost nobody needs, and best written up on the wiki.
- Remove Chocolatey and AUR which seem to be less frequently updated.
- Change GHC min version to 7.6.1.
=> Simplify download page, fix #32, fix #33, fix #36

README.md, package.json
* Adds the beginning of some development instructions. Missing some expanded notes on how Pandoc figures into all of this.
* Adds `grunt-cli` for seamless global-vs-local install workflows. (Some people don't have Grunt installed globally already, and are used to always-local installations of binaries; adding `grunt-cli` like this should work for both kinds of installations.)
=> Adds some stub instructions for working on the Purescript site.

learn/eff/index.markdown, learn/getting-started/index.markdown, learn/quickcheck/index.markdown
Replace references to 'pulp dep' with 'bower', since we're planning on
deprecating 'pulp dep'.
See also:
* https://github.com/bodil/pulp/pull/139
* https://github.com/bodil/pulp/issues/114
=> Remove references to pulp dep

_site/download/index.html, download/index.html
* Use --resolver=nightly for stack installation (we want people to
receive up-to-date versions)
* Update minimum required GHC version
Of course, the minimum required GHC version will only be 7.10.1 once psc
0.8.3 is released, so up to you whether to merge now or not.
=> Update download page

learn/eff/index.markdown
I believe that this is a small typo in the Eff tutorial.
=> Typo fix: Change application of firstName to fullName

learn/eff/index.markdown
Hi. This is just a minor update to the exceptions piece so that the provided example compiles (I imagine the `purescript-exceptions` module has undergone changes since this article was written).
Thanks.
=> Link to documentation and fix exception example.

_site/download/index.html, download/index.html
I dun goofed, sorry. :sweat_drops: 
(It got accidentally changed in the last round of copy edits. The link is different on each page [relative URLs, following the rest of the site]; the link from /learn got copied into /download.)
Follow-up from #81.
=> Fixes "Getting Started" link in /download.

site.hs
Windows, as ever, needs a little extra help to handle UTF8.
=> Use UTF8 locale

learn/getting-started/index.markdown
Will resolve #85.
I removed most of the references to `psc` as well as fixing the docs
link, as we don't really talk about `psc` in the article anymore since
Pulp is handling all the arguments and options when building.
=> Some tweaks to the getting started article

_site/download/index.html, _site/learn/eff/index.html, _site/learn/ffi/index.html, _site/learn/generic/index.html, _site/learn/getting-started/index.html, _site/learn/quickcheck/index.html, download/index.html
This has two main benefits over what we have currently:
It means that people end up using the same install plan that we use in
the binaries; currently, encouraging people to use nightly resolvers
will mean that they sometimes get new versions of libraries we depend
on, resulting in a set of dependencies which we haven't run the compiler
test suite with, or even used together.
It also means that people aren't limited to only those versions of
purescript which have made it into a nightly version. For example, when
we depend on some other package which isn't yet in the nightly snapshots
(for example, because not everything in the snapshot works with its
newer versions yet), that version of purescript would not be
installable. By contrast, this approach will work for any version of
PureScript …
=> Update download page to use stack unpack

learn/index.html
the blogpost doesn't work with the newest compiler. I've made a new blog today and will try to move the old blog posts over. Until then remove this dead link
=> Remove old blogpost

learn/eff/index.markdown
I just read the http://www.purescript.org/learn/eff/ documentation and came across this type signature:
```
foreign import unsafeRunCounter :: forall e. Eff (counter :: COUNTER | e) a -> Eff e a
```
I am new to purescript but if I understand it correctly the `a` type needs to be quantified as well.
=> Type signature in /learn/eff

learn/eff/index.markdown
Hi, I needed this fix to compile the `dividePure` example of [the Eff tutorial](http://www.purescript.org/learn/eff/) because:
- `dividePure` must return `Either String Int` instead of `Either Error Int`
- couldn't find `return` in the current PureScript documentation
I'm using PureScript 0.9.3.
=> Fix dividePure of Eff tutorial

_generator/index.html
Removed two imports for importing Flare and importing Flare.Drawing, but in _generator this time.
=> Fixed syntax

LICENSE
This applies to the new single-page content. It's the same license I use for the book.
Future contributions should be licensed under these terms. See https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license
> Whenever you make a contribution to a repository containing notice of a license, you license your contribution under the same terms, and you agree that you have the right to license your contribution under those terms. If you have a separate agreement to license your contributions under different terms, such as a contributor license agreement, that agreement will supersede.
> Isn't this just how it works already? Yep. This is widely accepted as the norm in the open-source community; it's commonly referred to by the shorthand …
=> Add CC-BY-SA-4.0 license

index.html
Node 6.x doesn't support object spread syntax, which is used in one of the dependencies of the npm package.
=> Update required Node version

index.html
=> Make spago the recommended build tool

index.html
Meetups deleted in https://github.com/purescript/documentation/pull/289
=> Update copywrite, delete meetups

index.html
These suggested additions to the front page of the website are made based on discussions from work while onboarding developers new to Purescript and also via more constructive Twitter discussions.
I added instructions on installing the `purescript` compile via Homebrew and also via Nix. I maintain the Nix package right now and plan to update it when newer versions of Purescript are released. The Homebrew formula for purescript is also fairly current.
I added the final note about how to manage JS dependencies because that has come up in multiple conversations with people new to Purescript trying to get ramped up.
Happy to amend.
=> Add note on recommended way to manage JavaScript dependencies via NPM and link to Spago

index.html
With the changes at freenode, seems like a good idea to remove the mentions of the channel from the website.
=> Remove mention of freenode IRC channel

index.html
This PR updates the link to the FP Slack to instead point to our PureScript Discord server. I've not included separate text about getting an invite vs. going to the server because the permanent invite link I've included will already either  a) allow the user to join the server or b) will take them directly to the server if they're already a member. 
We shouldn't deploy a new version of the site until July 26 when we're ready to migrate to Discord.
=> Update community link from Slack to Discord

discord/index.html
This PR introduces a HTML redirect for Discord, so that we can link to `purescript.org/discord` in documentation and have them get a usable invite link instead of to the link itself. This is an improvement because it means we can change the invite link going forward. Some examples of how that could happen:
* The server owner leaves, which will cause their permanent invite link to expire
* We change the default channel we invite people to
Once merged and tested, I intend to update our links to the old invite link to point to this instead.
=> Add a redirect for Discord
